version: '3.8'

services:
  api-gateway:
    container_name: api-gateway
    build: .
    ports:
      - "8080:8080"
    networks:
      - db

networks:
  db:
    external: true
    name: global-net

volumes:
  db: